enpal_assessment_project:
  outputs:
    dev:
      dbname: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      pass: admin
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: admin
  target: dev
